### ISSUE TITLE
run_regression giving an error

### ISSUE THREAD

**Issue by rue1996** [BayraktarLab/cell2location#107]
I am getting this error when i am running: training the model 

Traceback (most recent call last):
  File "/scratch/ms/visium_08_10_21/brain_visium_data/Allen_brain/allen_convert.py", line 44, in <module>
    r, adata_snrna_raw = run_regression(adata_snrna_raw, # input data object]
  File "/home/ms/.local/lib/python3.9/site-packages/cell2location/run_regression.py", line 144, in run_regression    X_data = sc_data.raw.X.toarray()
AttributeError: 'numpy.ndarray' object has no attribute 'toarray'

Not sure if it is still the issue that this only works with sparse.matrix and not numpy array?

**Comment by vitkl** [comment]
Hi

This interface is deprecated. Please install latest version and follow the
latest tutorial:
https://cell2location.readthedocs.io/en/latest/notebooks/cell2location_tutorial.html
