### ISSUE TITLE
error saving results [it is incorrect to use cell name as batch_key]

### ISSUE THREAD

**Issue by rue1996** [BayraktarLab/cell2location#109]
Hi

I am getting an error when saving the run regression model. 
This is the error I am getting
Traceback (most recent call last):
  File "/home/mshruv003/.local/lib/python3.9/site-packages/anndata/_io/utils.py", line 209, in func_wrapper
    return func(elem, key, val, *args, **kwargs)
  File "/home/mshruv003/.local/lib/python3.9/site-packages/anndata/_io/h5ad.py", line 258, in write_dataframe
    group.attrs["column-order"] = col_names
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/mshruv003/.local/lib/python3.9/site-packages/h5py/_hl/attrs.py", line 103, in __setitem__
    self.create(name, data=value)
  File "/home/mshruv003/.local/lib/python3.9/site-packages/h5py/_hl/attrs.py", line 196, in create
    attr = h5a.create(self._id, self._e(tempname), htype, space)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 50, in h5py.h5a.create
RuntimeError: Unable to create attribute (object header message is too large)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/mshruv003/visium_08_10_21/brain_visium_data/Allen_brain/allen_convert.py", line 88, in <module>
    r, adata_snrna_raw = run_regression(adata_snrna_raw, # input data object]
  File "/home/mshruv003/.local/lib/python3.9/site-packages/cell2location/run_regression.py", line 392, in run_regression
    sc_data.write(filename=path + "sc.h5ad", compression="gzip")
  File "/home/mshruv003/.local/lib/python3.9/site-packages/anndata/_core/anndata.py", line 1912, in write_h5ad
    _write_h5ad(
  File "/home/mshruv003/.local/lib/python3.9/site-packages/anndata/_io/h5ad.py", line 110, in write_h5ad
    write_attribute(f, "raw", adata.raw, dataset_kwargs=dataset_kwargs)
  File "/home/mshruv003/.conda/envs/cell2loc_env/lib/python3.9/functools.py", line 877, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/mshruv003/.local/lib/python3.9/site-packages/anndata/_io/h5ad.py", line 130, in write_attribute_h5ad
    _write_method(type(value))(f, key, value, *args, **kwargs)
  File "/home/mshruv003/.local/lib/python3.9/site-packages/anndata/_io/h5ad.py", line 139, in write_raw
    write_attribute(f, "raw/var", value.var, dataset_kwargs=dataset_kwargs)
  File "/home/mshruv003/.conda/envs/cell2loc_env/lib/python3.9/functools.py", line 877, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/mshruv003/.local/lib/python3.9/site-packages/anndata/_io/h5ad.py", line 130, in write_attribute_h5ad
    _write_method(type(value))(f, key, value, *args, **kwargs)
  File "/home/mshruv003/.local/lib/python3.9/site-packages/anndata/_io/utils.py", line 212, in func_wrapper
    raise type(e)(
RuntimeError: Unable to create attribute (object header message is too large)

I am using Allen brain data and it has two columns the sample_name (AAACCCACACTACTTT-LKTX_190129_01_A01) and exp_component_name (AAACCCACACTACTTT-21L8TX_180927_001_A01). I would like to know which of the two should i use as 'sample'. From reading the previous issues it might be because of using cell ID instead of sample ID. Could you please help me to understand this.

Thank you.

**Comment by vitkl** [comment]
Hi

Please use the revised tutorial and new scvi-tools interface (see docs
website). This will technically resolve the issue. That said we don't
recommend using the NB regression model for Smart-Seq 2 and other non-UMI
data because the data distribution doesn't satisfy the assumptions of our
model (it is zero inflated due to PCR amplification of detected RNA).
Please use the hard-coded computation of average expression:
https://cell2location.readthedocs.io/en/latest/cell2location.cluster_averages.html

**Comment by rue1996** [comment]
Hi

Thank you, the Allen brain data is 10X Genomics.

**Comment by vitkl** [comment]
Both columns that you mentioned look to me like these are cell IDs not 10X run aka inlet aka batch IDs. You can check how many cell you have per label with `adata.obs['sample_name'].value_counts()`.

**Comment by rue1996** [comment]
Okay, thank you.

**Comment by rue1996** [comment]
Hi Vitalii

Can i please get your assistance in running cell2location. I am very
excited and keen to make it work with my data. I am facing a couple of
issues that I am not sure how to solve.
1) The reference data that l have is Allen brain single cell atlas (human)
which is 10X. However their metadata does not contain the sample_id. Which
I looked for and found in another file. However the sample_ids rows are
less than the rows found in my Matrix file. So I am getting this error
: *ValueError:
Observations annot. `obs` must have a number of rows of `X` (76533), but
has 15928 rows.*
*I am not sure how to go about making the sample_ids the same as the number
of rows in my matrix data.*

2) On github you suggested I don't use the NB regression l use other models
that support the sample_name that l have in the metadata. However l am not
sure how to run that since there is no actual tutorial using other models.
Could you please give me guidance as to how l go about this?

Looking forward to hearing from you.

Regards
Ruvimbo

**Comment by vitkl** [comment]
> sample_name (AAACCCACACTACTTT-LKTX_190129_01_A01)

As I mentioned above and in the issue https://github.com/BayraktarLab/cell2location/issues/113, it is incorrect to use cell name as batch_key - because this creates a parameter for every gene and every cell. This also explains why you cannot save results - exported parameters are simply too large for h5ad format. 

> On github you suggested I don't use the NB regression l use other models that support the sample_name that l have in the metadata

Before, I knew that your data is 10X, I said to use the function https://cell2location.readthedocs.io/en/latest/cell2location.cluster_averages.html, I never said to use other models. 

> I am not sure how to go about making the sample_ids the same as the number
of rows in my matrix data.

You need to understand the data and data formats that you are working with. See https://anndata.readthedocs.io/en/latest/

**Comment by rue1996** [comment]
Thanks for the clear explanation.
