### ISSUE TITLE
error report when execute mod.train(max_epochs=250, train_size=1, lr=0.002, use_gpu=True)

### ISSUE THREAD

**Issue by sadiexiaoyu** [BayraktarLab/cell2location#120]
### Problem

I am running cell2location with my own dataset. I input the .h5ad file of the single nucleus cell RNAseq data (transformed from .rds file). And run cell2location.
Then it gives me the following warnings and error reports.
Could anyone give me any suggestion? Thanks!

>>> mod = RegressionModel(adata_ref)
/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/scvi_tools-0.14.5-py3.9.egg/scvi/model/base/_base_model.py:150: UserWarning: Make sure the registered X field in anndata contains unnormalized count data.
>>> mod.train(max_epochs=250, batch_size=2500, train_size=1, lr=0.002, use_gpu=True)
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pytorch_lightning-1.3.8-py3.9.egg/pytorch_lightning/trainer/configuration_validator.py:99: UserWarning: you passed in a val_dataloader but have no validation_step. Skipping val loop
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
Traceback (most recent call last):
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pyro_ppl-1.8.0-py3.9.egg/pyro/poutine/trace_messenger.py", line 174, in __call__
    ret = self.fn(*args, **kwargs)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pyro_ppl-1.8.0-py3.9.egg/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pyro_ppl-1.8.0-py3.9.egg/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pyro_ppl-1.8.0-py3.9.egg/pyro/nn/module.py", line 426, in __call__
    return super().__call__(*args, **kwargs)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/torch-1.10.2-py3.9-linux-x86_64.egg/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/cell2location-0.6a0-py3.9.egg/cell2location/models/reference/_reference_module.py", line 289, in forward
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pyro_ppl-1.8.0-py3.9.egg/pyro/distributions/distribution.py", line 18, in __call__
    return super().__call__(*args, **kwargs)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pyro_ppl-1.8.0-py3.9.egg/pyro/distributions/conjugate.py", line 252, in __init__
    self._gamma = Gamma(concentration, rate)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pyro_ppl-1.8.0-py3.9.egg/pyro/distributions/distribution.py", line 18, in __call__
    return super().__call__(*args, **kwargs)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/torch-1.10.2-py3.9-linux-x86_64.egg/torch/distributions/gamma.py", line 48, in __init__
    super(Gamma, self).__init__(batch_shape, validate_args=validate_args)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/torch-1.10.2-py3.9-linux-x86_64.egg/torch/distributions/distribution.py", line 55, in __init__
    raise ValueError(
ValueError: Expected parameter rate (Tensor of shape (2500, 1984)) of distribution Gamma(concentration: torch.Size([2500, 1984]), rate: torch.Size([2500, 1984])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[-1.9464e+01,  8.6002e+00, -6.3016e+01,  ..., -4.2161e+01,
          3.7086e+01, -2.5670e+01],
        [-2.2104e+01,  4.2921e+00, -5.4920e+01,  ...,  1.6326e+01,
         -2.1008e+01, -2.0423e+01],
        [-2.4070e+01, -1.7343e+01, -7.8625e+01,  ..., -4.2166e+01,
          4.1910e+01, -1.7174e+04],
        ...,
        [ 5.9818e+00, -1.8975e+01, -3.8527e+01,  ...,  3.0000e+01,
         -3.8819e+01,  1.8320e+01],
        [-2.4070e+01, -1.7343e+01, -7.8625e+01,  ..., -4.2166e+01,
          4.1910e+01, -1.7174e+04],
        [-2.2104e+01,  4.2921e+00, -5.4920e+01,  ...,  1.6326e+01,
         -2.1008e+01, -2.0423e+01]], device='cuda:0')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/cell2location-0.6a0-py3.9.egg/cell2location/models/reference/_reference_model.py", line 158, in train
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/scvi_tools-0.14.5-py3.9.egg/scvi/model/base/_pyromixin.py", line 145, in train
    return runner()
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/scvi_tools-0.14.5-py3.9.egg/scvi/train/_trainrunner.py", line 72, in __call__
    self.trainer.fit(self.training_plan, self.data_splitter)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/scvi_tools-0.14.5-py3.9.egg/scvi/train/_trainer.py", line 177, in fit
    super().fit(*args, **kwargs)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pytorch_lightning-1.3.8-py3.9.egg/pytorch_lightning/trainer/trainer.py", line 460, in fit
    self._run(model)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pytorch_lightning-1.3.8-py3.9.egg/pytorch_lightning/trainer/trainer.py", line 758, in _run
    self.dispatch()
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pytorch_lightning-1.3.8-py3.9.egg/pytorch_lightning/trainer/trainer.py", line 799, in dispatch
    self.accelerator.start_training(self)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pytorch_lightning-1.3.8-py3.9.egg/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pytorch_lightning-1.3.8-py3.9.egg/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training
    self._results = trainer.run_stage()
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pytorch_lightning-1.3.8-py3.9.egg/pytorch_lightning/trainer/trainer.py", line 809, in run_stage
    return self.run_train()
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pytorch_lightning-1.3.8-py3.9.egg/pytorch_lightning/trainer/trainer.py", line 857, in run_train
    self.train_loop.on_train_start()
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pytorch_lightning-1.3.8-py3.9.egg/pytorch_lightning/trainer/training_loop.py", line 101, in on_train_start
    self.trainer.call_hook("on_train_start")
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pytorch_lightning-1.3.8-py3.9.egg/pytorch_lightning/trainer/trainer.py", line 1228, in call_hook
    trainer_hook(*args, **kwargs)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pytorch_lightning-1.3.8-py3.9.egg/pytorch_lightning/trainer/callback_hook.py", line 152, in on_train_start
    callback.on_train_start(self, self.lightning_module)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/scvi_tools-0.14.5-py3.9.egg/scvi/model/base/_pyromixin.py", line 47, in on_train_start
    pyro_guide(*args, **kwargs)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pyro_ppl-1.8.0-py3.9.egg/pyro/nn/module.py", line 426, in __call__
    return super().__call__(*args, **kwargs)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/torch-1.10.2-py3.9-linux-x86_64.egg/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pyro_ppl-1.8.0-py3.9.egg/pyro/infer/autoguide/guides.py", line 510, in forward
    self._setup_prototype(*args, **kwargs)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pyro_ppl-1.8.0-py3.9.egg/pyro/infer/autoguide/guides.py", line 460, in _setup_prototype
    super()._setup_prototype(*args, **kwargs)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pyro_ppl-1.8.0-py3.9.egg/pyro/infer/autoguide/guides.py", line 157, in _setup_prototype
    self.prototype_trace = poutine.block(poutine.trace(model).get_trace)(
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pyro_ppl-1.8.0-py3.9.egg/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pyro_ppl-1.8.0-py3.9.egg/pyro/poutine/trace_messenger.py", line 198, in get_trace
    self(*args, **kwargs)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pyro_ppl-1.8.0-py3.9.egg/pyro/poutine/trace_messenger.py", line 180, in __call__
    raise exc from e
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pyro_ppl-1.8.0-py3.9.egg/pyro/poutine/trace_messenger.py", line 174, in __call__
    ret = self.fn(*args, **kwargs)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pyro_ppl-1.8.0-py3.9.egg/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pyro_ppl-1.8.0-py3.9.egg/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pyro_ppl-1.8.0-py3.9.egg/pyro/nn/module.py", line 426, in __call__
    return super().__call__(*args, **kwargs)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/torch-1.10.2-py3.9-linux-x86_64.egg/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/cell2location-0.6a0-py3.9.egg/cell2location/models/reference/_reference_module.py", line 289, in forward
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pyro_ppl-1.8.0-py3.9.egg/pyro/distributions/distribution.py", line 18, in __call__
    return super().__call__(*args, **kwargs)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pyro_ppl-1.8.0-py3.9.egg/pyro/distributions/conjugate.py", line 252, in __init__
    self._gamma = Gamma(concentration, rate)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/pyro_ppl-1.8.0-py3.9.egg/pyro/distributions/distribution.py", line 18, in __call__
    return super().__call__(*args, **kwargs)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/torch-1.10.2-py3.9-linux-x86_64.egg/torch/distributions/gamma.py", line 48, in __init__
    super(Gamma, self).__init__(batch_shape, validate_args=validate_args)
  File "/GPUFS/sysu_lygu_2/anaconda3/envs/cell2location/lib/python3.9/site-packages/torch-1.10.2-py3.9-linux-x86_64.egg/torch/distributions/distribution.py", line 55, in __init__
    raise ValueError(
ValueError: Expected parameter rate (Tensor of shape (2500, 1984)) of distribution Gamma(concentration: torch.Size([2500, 1984]), rate: torch.Size([2500, 1984])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[-1.9464e+01,  8.6002e+00, -6.3016e+01,  ..., -4.2161e+01,
          3.7086e+01, -2.5670e+01],
        [-2.2104e+01,  4.2921e+00, -5.4920e+01,  ...,  1.6326e+01,
         -2.1008e+01, -2.0423e+01],
        [-2.4070e+01, -1.7343e+01, -7.8625e+01,  ..., -4.2166e+01,
          4.1910e+01, -1.7174e+04],
        ...,
        [ 5.9818e+00, -1.8975e+01, -3.8527e+01,  ...,  3.0000e+01,
         -3.8819e+01,  1.8320e+01],
        [-2.4070e+01, -1.7343e+01, -7.8625e+01,  ..., -4.2166e+01,
          4.1910e+01, -1.7174e+04],
        [-2.2104e+01,  4.2921e+00, -5.4920e+01,  ...,  1.6326e+01,
         -2.1008e+01, -2.0423e+01]], device='cuda:0')
                Trace Shapes:         
                 Param Sites:         
                Sample Sites:         
       per_cluster_mu_fg dist | 5 1984
                        value | 5 1984
      detection_mean_y_e dist | 1    1
                        value | 1    1
  s_g_gene_add_alpha_hyp dist |       
                        value |       
       s_g_gene_add_mean dist | 1    1
                        value | 1    1
s_g_gene_add_alpha_e_inv dist | 1    1
                        value | 1    1
            s_g_gene_add dist | 1 1984
                        value | 1 1984
         alpha_g_phi_hyp dist |       
                        value |       
         alpha_g_inverse dist | 1 1984
                        value | 1 1984

**Comment by vitkl** [comment]
Hi @sadiexiaoyu 

Both the regression model for scRNA data and the main cell2location model require raw/untransformed/unnormalised counts - make sure that you are providing that as input.
