### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by liukc19** [BayraktarLab/cell2location#146]
### Problem
I try this installation command
`pip install git+https://github.com/BayraktarLab/cell2location.git#egg=cell2location[tutorials]`
but the it takes a quite long time and still didn't finish installing
errors like this:
```
INFO: pip is looking at multiple versions of netcdf4 to determine which version is compatible with other requirements. This could take a while.
Collecting netcdf4
  Using cached netCDF4-1.5.7-cp39-cp39-win_amd64.whl (3.2 MB)
  Using cached netCDF4-1.5.6-cp39-cp39-win_amd64.whl (3.1 MB)
  Using cached netCDF4-1.5.5.1-cp39-cp39-win_amd64.whl (3.1 MB)
  Using cached netCDF4-1.5.5-cp39-cp39-win_amd64.whl (3.1 MB)
  Using cached netCDF4-1.5.4-cp39-cp39-win_amd64.whl (3.1 MB)
  Using cached netCDF4-1.5.3.tar.gz (790 kB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\Users\Adam\anaconda3\envs\cell2loc_env\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Adam\\AppData\\Local\\Temp\\pip-install-81quue4v\\netcdf4_a6a20af572f44352bacafec796bf6201\\setup.py'"'"'; __file__='"'"'C:\\Users\\Adam\\AppData\\Local\\Temp\\pip-install-81quue4v\\netcdf4_a6a20af572f44352bacafec796bf6201\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Adam\AppData\Local\Temp\pip-pip-egg-info-uyo34nm_'
         cwd: C:\Users\Adam\AppData\Local\Temp\pip-install-81quue4v\netcdf4_a6a20af572f44352bacafec796bf6201\
    Complete output (16 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Adam\AppData\Local\Temp\pip-install-81quue4v\netcdf4_a6a20af572f44352bacafec796bf6201\setup.py", line 397, in <module>
        _populate_hdf5_info(dirstosearch, inc_dirs, libs, lib_dirs)
      File "C:\Users\Adam\AppData\Local\Temp\pip-install-81quue4v\netcdf4_a6a20af572f44352bacafec796bf6201\setup.py", line 345, in _populate_hdf5_info
        raise ValueError('did not find HDF5 headers')
    ValueError: did not find HDF5 headers
    reading from setup.cfg...

        HDF5_DIR environment variable not set, checking some standard locations ..
    checking C:\Users\Adam ...
    checking /usr/local ...
    checking /sw ...
    checking /opt ...
    checking /opt/local ...
    checking /usr ...
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/cd/ee/b7734f8fb94c9671b6966f158903cd3b67cb60d245c6f2196bcf1f8b13b5/netCDF4-1.5.3.tar.gz#sha256=2a3ca855848f4bbf07fac366da77a681fcead18c0a8813d91d46302f562dc3be (from https://pypi.org/simple/netcdf4/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached netCDF4-1.5.2.tar.gz (801 kB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\Users\Adam\anaconda3\envs\cell2loc_env\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Adam\\AppData\\Local\\Temp\\pip-install-81quue4v\\netcdf4_187fb8b3e5d1415aa3332168495bbe0e\\setup.py'"'"'; __file__='"'"'C:\\Users\\Adam\\AppData\\Local\\Temp\\pip-install-81quue4v\\netcdf4_187fb8b3e5d1415aa3332168495bbe0e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Adam\AppData\Local\Temp\pip-pip-egg-info-51fh7ouo'
         cwd: C:\Users\Adam\AppData\Local\Temp\pip-install-81quue4v\netcdf4_187fb8b3e5d1415aa3332168495bbe0e\
    Complete output (16 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Adam\AppData\Local\Temp\pip-install-81quue4v\netcdf4_187fb8b3e5d1415aa3332168495bbe0e\setup.py", line 397, in <module>
        _populate_hdf5_info(dirstosearch, inc_dirs, libs, lib_dirs)
      File "C:\Users\Adam\AppData\Local\Temp\pip-install-81quue4v\netcdf4_187fb8b3e5d1415aa3332168495bbe0e\setup.py", line 345, in _populate_hdf5_info
        raise ValueError('did not find HDF5 headers')
    ValueError: did not find HDF5 headers
    reading from setup.cfg...

        HDF5_DIR environment variable not set, checking some standard locations ..
    checking C:\Users\Adam ...
    checking /usr/local ...
    checking /sw ...
    checking /opt ...
    checking /opt/local ...
    checking /usr ...
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/64/2e/abc0bce095ab5a3b8374f052ace2509a031fd7633b23917e557487067225/netCDF4-1.5.2.tar.gz#sha256=e075e1937ae5b297292c22adb72d7fdf557ba7509e6fd967fec133f1be178922 (from https://pypi.org/simple/netcdf4/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached netCDF4-1.5.1.2.tar.gz (808 kB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\Users\Adam\anaconda3\envs\cell2loc_env\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Adam\\AppData\\Local\\Temp\\pip-install-81quue4v\\netcdf4_b9891943c4fe41ba8a448dc5d603a1a2\\setup.py'"'"'; __file__='"'"'C:\\Users\\Adam\\AppData\\Local\\Temp\\pip-install-81quue4v\\netcdf4_b9891943c4fe41ba8a448dc5d603a1a2\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Adam\AppData\Local\Temp\pip-pip-egg-info-gkt7o095'
         cwd: C:\Users\Adam\AppData\Local\Temp\pip-install-81quue4v\netcdf4_b9891943c4fe41ba8a448dc5d603a1a2\
    Complete output (18 lines):
    C:\Users\Adam\AppData\Local\Temp\pip-install-81quue4v\netcdf4_b9891943c4fe41ba8a448dc5d603a1a2\setup.py:185: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
      config = configparser.SafeConfigParser()
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Adam\AppData\Local\Temp\pip-install-81quue4v\netcdf4_b9891943c4fe41ba8a448dc5d603a1a2\setup.py", line 386, in <module>
        _populate_hdf5_info(dirstosearch, inc_dirs, libs, lib_dirs)
      File "C:\Users\Adam\AppData\Local\Temp\pip-install-81quue4v\netcdf4_b9891943c4fe41ba8a448dc5d603a1a2\setup.py", line 334, in _populate_hdf5_info
        raise ValueError('did not find HDF5 headers')
    ValueError: did not find HDF5 headers
    reading from setup.cfg...

        HDF5_DIR environment variable not set, checking some standard locations ..
    checking C:\Users\Adam ...
    checking /usr/local ...
    checking /sw ...
    checking /opt ...
    checking /opt/local ...
    checking /usr ...
    ------------------
 ```

...

- [x] I follow the instructions from the [cell2location tutorial (using on scvi-tools)](https://cell2location.readthedocs.io/en/latest/notebooks/cell2location_tutorial.html).
- [ ] I have adjusted required hyperparameters to my dataset and tissue `N_cells_per_location` and `detection_alpha`.
- [ ] I have provided 10X reaction/inlet as `batch_key` for reference NB regression.
- [ ] I have checked [scverse Discourse](https://discourse.scverse.org/c/ecosytem/cell2location/) and [old Cell2location Community Forum](https://github.com/BayraktarLab/cell2location/discussions), and did not find a solution.

### Description of the data input and hyperparameters

...

...

#### Single cell reference data: number of cells, number of cell types, number of genes

...

#### Single cell reference data: technology type (e.g. mix of 10X 3' and 5')

...

#### Spatial data: number of locations numbers, technology type (e.g. Visium, ISS, Nanostring WTA)

...

**Comment by vitkl** [comment]
Hi @liukc19 

Thanks for using cell2location. We have not tested cell2location with Windows system. I know @nadavyayon tried this and maybe he can comment.

I can recommend using conda to install problematic packages: 
```
export PYTHONNOUSERSITE="aaaaa"
conda create -y -n c2l python=3.8
conda activate c2l
conda install -y -c anaconda hdf5 pytables netcdf4
pip install git+https://github.com/BayraktarLab/cell2location.git#egg=cell2location[tutorials]
```

**Comment by nadavyayon** [comment]
Hi @liukc19 !

Unfortunately I also recently tried to install C2L on a windows system with an RTX3090 without success and eventually switched back to our farm GPU machines. But please keep me posted if you find a stable combination. 

Best 

Nadav

**Comment by vitkl** [comment]
@nadavyayon did you have issues with h5 and netCDF4 related packages OR did you have issues with GPU-related packages (pytorch/pyro, cell2location without tutorials option)?

Issues with the former are not issues specific to cell2location - but issues with scanpy/anndata on that system. Did you succeed with creating environments with scanpy alone (https://scanpy.readthedocs.io/en/stable/installation.html)?
I find that on Mac the same packages create a problem and need to be installed using conda before installing cell2location with pip.

If you have GPU-related issues you can try installing pytorch, pyro alone and running any pytorch test code. Based on what @yozhikoff is telling me - this should work.

**Comment by vitkl** [comment]
@liukc19 @nadavyayon  You can also ask this question on https://discourse.scverse.org/c/ecosytem/cell2location/ where more people can respond and look for scvi-tools tips for Windows.
