### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by QqQss** [BayraktarLab/cell2location#15]
Hi guys,

I have tried to install your package many times (both method 1 or method 2). The installation process went successfully, but return an error during import.

Here is the error:
```
>>> import cell2location
/miniconda3/envs/cellpymc/lib/python3.7/site-packages/theano/configdefaults.py:17: TheanoConfigWarning: Config key '/raid1/qinshishang/tmp_cache/' has no value, ignoring it
  from theano.configparser import (AddConfigVar, BoolParam, ConfigParam, EnumStr,
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/miniconda3/envs/cellpymc/lib/python3.7/site-packages/cell2location/__init__.py", line 2, in <module>
    from .run_c2l import run_cell2location
  File "/miniconda3/envs/cellpymc/lib/python3.7/site-packages/cell2location/run_c2l.py", line 9, in <module>
    import theano
  File "/miniconda3/envs/cellpymc/lib/python3.7/site-packages/theano/__init__.py", line 110, in <module>
    from theano.compile import (
  File "/miniconda3/envs/cellpymc/lib/python3.7/site-packages/theano/compile/__init__.py", line 28, in <module>
    from theano.compile.function import function, function_dump
  File "/miniconda3/envs/cellpymc/lib/python3.7/site-packages/theano/compile/function/__init__.py", line 7, in <module>
    from theano.compile.function.pfunc import pfunc
  File "/miniconda3/envs/cellpymc/lib/python3.7/site-packages/theano/compile/function/pfunc.py", line 10, in <module>
    from theano.compile.function.types import UnusedInputError, orig_function
  File "/miniconda3/envs/cellpymc/lib/python3.7/site-packages/theano/compile/function/types.py", line 23, in <module>
    from theano.gof.toolbox import is_same_graph
ImportError: cannot import name 'is_same_graph' from 'theano.gof.toolbox' (/miniconda3/envs/cellpymc/lib/python3.7/site-packages/theano/gof/toolbox.py)
```
So, I wonder how to deal with that? could anyone give me some suggestions?

**Comment by vitkl** [comment]
Hi @QqQss,

Thanks for using our package! This issue arises from very recent changes to pymc3. I have just updated `environment.yml` and installation instructions to use `pymc3>=3.8,<3.10`. Please try installing again now.

You can also use our docker and singularity images to avoid this and potentially other issues with installing cell2location your system.

**Comment by QqQss** [comment]
It works! Thanks!
