### ISSUE TITLE
Fail to import cell2location in HPC

### ISSUE THREAD

**Issue by WT215** [BayraktarLab/cell2location#170]
Hello,

I follow the instruction for installing the package:
```
export PYTHONNOUSERSITE="literallyanyletters"
conda create -y -n cell2loc_env python=3.9
conda activate cell2loc_env
pip install git+https://github.com/BayraktarLab/cell2location.git#egg=cell2location[tutorials]
```

Then, I tried to import it, but there is error with `jaxlib`.

```python
>>> import cell2location
```

```pytb
Global seed set to 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ma/w/wt215/anaconda3/envs/cell2loc_env/lib/python3.9/site-packages/cell2location/__init__.py", line 5, in <module>
    from . import models
  File "/home/ma/w/wt215/anaconda3/envs/cell2loc_env/lib/python3.9/site-packages/cell2location/models/__init__.py", line 1, in <module>
    from ._cell2location_model import Cell2location
  File "/home/ma/w/wt215/anaconda3/envs/cell2loc_env/lib/python3.9/site-packages/cell2location/models/_cell2location_model.py", line 11, in <module>
    from scvi import REGISTRY_KEYS
  File "/home/ma/w/wt215/anaconda3/envs/cell2loc_env/lib/python3.9/site-packages/scvi/__init__.py", line 10, in <module>
    from . import data, model, external, utils
  File "/home/ma/w/wt215/anaconda3/envs/cell2loc_env/lib/python3.9/site-packages/scvi/data/__init__.py", line 24, in <module>
    from ._manager import AnnDataManager
  File "/home/ma/w/wt215/anaconda3/envs/cell2loc_env/lib/python3.9/site-packages/scvi/data/_manager.py", line 15, in <module>
    from scvi._types import AnnDataField
  File "/home/ma/w/wt215/anaconda3/envs/cell2loc_env/lib/python3.9/site-packages/scvi/_types.py", line 3, in <module>
    import jax.numpy as jnp
  File "/home/ma/w/wt215/anaconda3/envs/cell2loc_env/lib/python3.9/site-packages/jax/__init__.py", line 35, in <module>
    from jax import config as _config_module
  File "/home/ma/w/wt215/anaconda3/envs/cell2loc_env/lib/python3.9/site-packages/jax/config.py", line 17, in <module>
    from jax._src.config import config
  File "/home/ma/w/wt215/anaconda3/envs/cell2loc_env/lib/python3.9/site-packages/jax/_src/config.py", line 27, in <module>
    from jax._src import lib
  File "/home/ma/w/wt215/anaconda3/envs/cell2loc_env/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 113, in <module>
    cpu_feature_guard.check_cpu_features()
RuntimeError: This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. You may be able work around this issue by building jaxlib from source.
```
CPU:
```
$ sed -n '/^model name/p' /proc/cpuinfo | uniq      model name      : Intel(R) Xeon(R) CPU           X5570  @ 2.93GHz
$ sed -n '/^flags/p' /proc/cpuinfo | uniq | grep -i --color avx
(nothing printed out in second command)
```

Many thanks!

**Comment by WT215** [comment]
should be a question, not a bug

**Comment by WT215** [comment]
The versions of jax and jaxlib are as the same as shown in the tutorial.
"""
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
absl-py                   1.1.0                    pypi_0    pypi
aiohttp                   3.8.1                    pypi_0    pypi
aiosignal                 1.2.0                    pypi_0    pypi
anndata                   0.8.0                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
asttokens                 2.0.5                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     21.4.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.11.1                   pypi_0    pypi
bleach                    5.0.0                    pypi_0    pypi
ca-certificates           2022.4.26            h06a4308_0
cachetools                5.2.0                    pypi_0    pypi
cell2location             0.1                      pypi_0    pypi
certifi                   2022.5.18.1      py39h06a4308_0
cffi                      1.15.0                   pypi_0    pypi
charset-normalizer        2.0.12                   pypi_0    pypi
chex                      0.1.3                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
commonmark                0.9.1                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
debugpy                   1.6.0                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
dm-tree                   0.1.7                    pypi_0    pypi
docrep                    0.3.2                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
et-xmlfile                1.1.0                    pypi_0    pypi
executing                 0.8.3                    pypi_0    pypi
fastjsonschema            2.15.3                   pypi_0    pypi
flatbuffers               2.0                      pypi_0    pypi
flax                      0.5.1                    pypi_0    pypi
fonttools                 4.33.3                   pypi_0    pypi
frozenlist                1.3.0                    pypi_0    pypi
fsspec                    2022.5.0                 pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
google-auth               2.8.0                    pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.46.3                   pypi_0    pypi
h5py                      3.7.0                    pypi_0    pypi
idna                      3.3                      pypi_0    pypi
igraph                    0.9.11                   pypi_0    pypi
importlib-metadata        4.11.4                   pypi_0    pypi
ipykernel                 6.15.0                   pypi_0    pypi
ipython                   8.4.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.7.0                    pypi_0    pypi
**jax                       0.3.13                   pypi_0    pypi
jaxlib                    0.3.10                   pypi_0    pypi**
jedi                      0.18.1                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
jsonschema                4.6.0                    pypi_0    pypi
jupyter-client            7.3.4                    pypi_0    pypi
jupyter-core              4.10.0                   pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-widgets        1.1.0                    pypi_0    pypi
kiwisolver                1.4.3                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1
leidenalg                 0.8.10                   pypi_0    pypi
libffi                    3.3                  he6710b0_2
libgcc-ng                 11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
libstdcxx-ng              11.2.0               h1234567_1
llvmlite                  0.38.1                   pypi_0    pypi
markdown                  3.3.7                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.5.2                    pypi_0    pypi
matplotlib-inline         0.1.3                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
msgpack                   1.0.4                    pypi_0    pypi
multidict                 6.0.2                    pypi_0    pypi
multipledispatch          0.6.0                    pypi_0    pypi
natsort                   8.1.0                    pypi_0    pypi
nbclient                  0.6.4                    pypi_0    pypi
nbconvert                 6.5.0                    pypi_0    pypi
nbformat                  5.4.0                    pypi_0    pypi
ncurses                   6.3                  h7f8727e_2
nest-asyncio              1.5.5                    pypi_0    pypi
networkx                  2.8.4                    pypi_0    pypi
notebook                  6.4.12                   pypi_0    pypi
numba                     0.55.2                   pypi_0    pypi
numpy                     1.22.4                   pypi_0    pypi
numpyro                   0.9.2                    pypi_0    pypi
oauthlib                  3.2.0                    pypi_0    pypi
opencv-python             4.6.0.66                 pypi_0    pypi
openpyxl                  3.0.10                   pypi_0    pypi
openssl                   1.1.1o               h7f8727e_0
opt-einsum                3.3.0                    pypi_0    pypi
optax                     0.1.2                    pypi_0    pypi
packaging                 21.3                     pypi_0    pypi
pandas                    1.4.2                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
patsy                     0.5.2                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.1.1                    pypi_0    pypi
pip                       21.2.4           py39h06a4308_0
prometheus-client         0.14.1                   pypi_0    pypi
prompt-toolkit            3.0.29                   pypi_0    pypi
protobuf                  3.20.1                   pypi_0    pypi
psutil                    5.9.1                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pydeprecate               0.3.1                    pypi_0    pypi
pygments                  2.12.0                   pypi_0    pypi
pynndescent               0.5.7                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyro-api                  0.1.2                    pypi_0    pypi
pyro-ppl                  1.8.1                    pypi_0    pypi
pyrsistent                0.18.1                   pypi_0    pypi
python                    3.9.12               h12debd9_1
python-dateutil           2.8.2                    pypi_0    pypi
python-igraph             0.9.11                   pypi_0    pypi
pytorch-lightning         1.5.10                   pypi_0    pypi
pytz                      2022.1                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     23.1.0                   pypi_0    pypi
readline                  8.1.2                h7f8727e_1
requests                  2.28.0                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rich                      11.1.0                   pypi_0    pypi
rsa                       4.8                      pypi_0    pypi
scanpy                    1.9.1                    pypi_0    pypi
scikit-learn              1.1.1                    pypi_0    pypi
scipy                     1.8.1                    pypi_0    pypi
scvi-tools                0.16.4                   pypi_0    pypi
seaborn                   0.11.2                   pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
session-info              1.0.0                    pypi_0    pypi
setuptools                59.5.0                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
soupsieve                 2.3.2.post1              pypi_0    pypi
sqlite                    3.38.3               hc218d9a_0
stack-data                0.3.0                    pypi_0    pypi
statsmodels               0.13.2                   pypi_0    pypi
stdlib-list               0.8.0                    pypi_0    pypi
tensorboard               2.9.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
terminado                 0.15.0                   pypi_0    pypi
texttable                 1.6.4                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tinycss2                  1.1.1                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0
toolz                     0.11.2                   pypi_0    pypi
torch                     1.11.0                   pypi_0    pypi
torchmetrics              0.9.1                    pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
tqdm                      4.64.0                   pypi_0    pypi
traitlets                 5.2.2.post1              pypi_0    pypi
typing-extensions         4.2.0                    pypi_0    pypi
tzdata                    2022a                hda174b7_0
umap-learn                0.5.3                    pypi_0    pypi
urllib3                   1.26.9                   pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
werkzeug                  2.1.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0
widgetsnbextension        3.6.0                    pypi_0    pypi
xz                        5.2.5                h7f8727e_1
yarl                      1.7.2                    pypi_0    pypi
zipp                      3.8.0                    pypi_0    pypi
zlib                      1.2.12               h7f8727e_2

"""

**Comment by WT215** [comment]
Solved. It is platform's problem.
