### ISSUE TITLE
ValueError in mod.train() running on HPC

### ISSUE THREAD

**Issue by wangxin2873** [BayraktarLab/cell2location#294]
### Problem

- [ ] I am running the spatial mapping train following the instructions from the [cell2location tutorial (using on scvi-tools)].
- [ ] I can finish training the mod using mod.train() in my PC for max_epochs=2000.
- [ ] However, when I submit the same code into the High Performance Computer of the University. A ValueError occured.
```python
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
SLURM auto-requeueing enabled. Setting signal handlers.
Traceback (most recent call last):
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/pyro/poutine/trace_messenger.py", line 174, in __call__
    ret = self.fn(*args, **kwargs)
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/pyro/nn/module.py", line 449, in __call__
    result = super().__call__(*args, **kwargs)
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/cell2location/models/_cell2location_module.py", line 386, in forward
    dist.Gamma(
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/pyro/distributions/distribution.py", line 24, in __call__
    return super().__call__(*args, **kwargs)
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/torch/distributions/gamma.py", line 54, in __init__
    super(Gamma, self).__init__(batch_shape, validate_args=validate_args)
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/torch/distributions/distribution.py", line 56, in __init__
    raise ValueError(
ValueError: Expected parameter rate (Tensor of shape (1, 1)) of distribution Gamma(concentration: tensor([[10.]], device='cuda:0'), rate: tensor([[nan]], device='cuda:0')) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[nan]], device='cuda:0')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/public/home/liuqing/wx/scspgc/cell2loc/cell2_train.py", line 49, in <module>
    mod.train(max_epochs=30000,##default30000
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/cell2location/models/_cell2location_model.py", line 209, in train
    super().train(**kwargs)
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/scvi/model/base/_pyromixin.py", line 182, in train
    return runner()
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/scvi/train/_trainrunner.py", line 99, in __call__
    self.trainer.fit(self.training_plan, self.data_splitter)
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/scvi/train/_trainer.py", line 186, in fit
    super().fit(*args, **kwargs)
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 529, in fit
    call._call_and_handle_interrupt(
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 568, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 973, in _run
    results = self._run_stage()
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 1016, in _run_stage
    self.fit_loop.run()
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/lightning/pytorch/loops/fit_loop.py", line 197, in run
    self.on_run_start()
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/lightning/pytorch/loops/fit_loop.py", line 315, in on_run_start
    call._call_callback_hooks(trainer, "on_train_start")
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 193, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/scvi/model/base/_pyromixin.py", line 44, in on_train_start
    pyro_guide(*args, **kwargs)
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/pyro/nn/module.py", line 449, in __call__
    result = super().__call__(*args, **kwargs)
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/pyro/infer/autoguide/guides.py", line 510, in forward
    self._setup_prototype(*args, **kwargs)
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/pyro/infer/autoguide/guides.py", line 460, in _setup_prototype
    super()._setup_prototype(*args, **kwargs)
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/pyro/infer/autoguide/guides.py", line 157, in _setup_prototype
    self.prototype_trace = poutine.block(poutine.trace(model).get_trace)(
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/pyro/poutine/trace_messenger.py", line 198, in get_trace
    self(*args, **kwargs)
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/pyro/poutine/trace_messenger.py", line 180, in __call__
    raise exc from e
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/pyro/poutine/trace_messenger.py", line 174, in __call__
    ret = self.fn(*args, **kwargs)
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/pyro/nn/module.py", line 449, in __call__
    result = super().__call__(*args, **kwargs)
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/cell2location/models/_cell2location_module.py", line 386, in forward
    dist.Gamma(
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/pyro/distributions/distribution.py", line 24, in __call__
    return super().__call__(*args, **kwargs)
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/torch/distributions/gamma.py", line 54, in __init__
    super(Gamma, self).__init__(batch_shape, validate_args=validate_args)
  File "/public/home/liuqing/miniconda3/envs/test_scvi16_cuda113/lib/python3.9/site-packages/torch/distributions/distribution.py", line 56, in __init__
    raise ValueError(
ValueError: Expected parameter rate (Tensor of shape (1, 1)) of distribution Gamma(concentration: tensor([[10.]], device='cuda:0'), rate: tensor([[nan]], device='cuda:0')) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[nan]], device='cuda:0')
               Trace Shapes:                
                Param Sites:                
               Sample Sites:                
               m_g_mean dist          |  1 1
                       value          |  1 1
        m_g_alpha_e_inv dist          |  1 1
                       value          |  1 1
                    m_g dist          |  1 0
                       value          |  1 0
 n_s_cells_per_location dist 28741  1 |     
                       value 28741  1 |     
b_s_groups_per_location dist 28741  1 |     
                       value 28741  1 |     
    z_sr_groups_factors dist 28741 50 |     
                       value 28741 50 |     
 k_r_factors_per_groups dist          | 50 1
                       value          | 50 1
        x_fr_group2fact dist          | 50 0
                       value          | 50 0
                   w_sf dist 28741  0 |     
                       value 28741  0 |     
srun: error: node111: task 0: Exited with exit code 1
``` 
The GPU in HPC 
![mmexport1689945381860](https://github.com/BayraktarLab/cell2location/assets/104182668/a8f05083-d42f-435e-b869-26afdc95d695)
GPU in my PC
![mmexport1689945383107](https://github.com/BayraktarLab/cell2location/assets/104182668/a9d491e1-c0e1-4546-811d-fb37f035833b)

**Comment by vitkl** [comment]
Hi @wangxin2873 

Does the script fail immediately on HPC or after 2000k steps?

Immediate error would suggest input issues.

**Comment by Zhangnshuo** [comment]
i ran into the same issue, it happened immediately
