### ISSUE TITLE
plot spatial error with multiple slides

### ISSUE THREAD

**Issue by jil100** [BayraktarLab/cell2location#321]
I followed the latest tutorial (https://cell2location.readthedocs.io/en/latest/notebooks/cell2location_tutorial.html) and was able to reproduce the results successfully. When I used my own data with multiple slides, I followed the tutorial (https://cell2location.readthedocs.io/en/latest/notebooks/cell2location_short_demo.html#1.-Loading-Visium-data) to load the visium data, then proceeded with the latest tutorial. An error occurred as follows:

```python
fig = mod.plot_spatial_QC_across_batches()
```
```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/il55/cell2loc_env/lib/python3.9/site-packages/cell2location/models/_cell2location_model.py", line 421, in plot_spatial_QC_across_batches
    scanpy.pl.spatial(
  File "/home/il55/cell2loc_env/lib/python3.9/site-packages/scanpy/plotting/_tools/scatterplots.py", line 1002, in spatial
    axs = embedding(
  File "/home/il55/cell2loc_env/lib/python3.9/site-packages/scanpy/plotting/_tools/scatterplots.py", line 391, in embedding
    cax = scatter(
  File "/home/il55/cell2loc_env/lib/python3.9/site-packages/scanpy/plotting/_utils.py", line 1107, in circles
    x = x * scale_factor
TypeError: can't multiply sequence by non-int of type 'float'
```
The same error occurred when I tried to plot cell abundance in spatial coordinates:
```python
from cell2location.utils import select_slide
slide = select_slide(adata_vis, 'A1')

with mpl.rc_context({'axes.facecolor':  'black',
                     'figure.figsize': [4.5, 5]}):
    sc.pl.spatial(slide, cmap='magma',
                  color=['CD14+Mo', 'CD16+Mo', 'MoMP', 'LYVE1+IGF1+MP', 'LYVE1+TIMD4+MP',
                  'LYVE1+MP_cycling', 'DC', 'Neut'],
                  ncols=4, size=1.3,
                  img_key='hires',
                  # limit color scale at 99.2% quantile of cell abundance
                  vmin=0, vmax='p99.2'
                 )
```
```pytb
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/il55/cell2loc_env/lib/python3.9/site-packages/scanpy/plotting/_tools/scatterplots.py", line 1002, in spatial
    axs = embedding(
  File "/home/il55/cell2loc_env/lib/python3.9/site-packages/scanpy/plotting/_tools/scatterplots.py", line 391, in embedding
    cax = scatter(
  File "/home/il55/cell2loc_env/lib/python3.9/site-packages/scanpy/plotting/_utils.py", line 1107, in circles
    x = x * scale_factor
TypeError: can't multiply sequence by non-int of type 'float'
```

**Comment by vitkl** [comment]
Hi @jil100 

as you note with your second example, this is an issue with scanpy spatial plotting (related to `scale_factor`) rather than with cell2location. Can you plot the expression of genes? If you get the same error with gene plotting I would suggest creating an issue with scanpy package.

**Comment by jil100** [comment]
@vitkl  

Thank you for the quick response. It did seem to be a scanpy spatial plotting issue, and I was able to plot cell abundance in spatial coordinates after I followed the suggestion given in https://github.com/scverse/scanpy/issues/2499 (although I still got the same error for  ` fig = mod.plot_spatial_QC_across_batches()`).  However, when I tried to save the adata_vis as follows:

```python
adata_file = f"{run_name}/sp.h5ad"
adata_vis.write(adata_file)
```
I got the following errors:
```pytb
Traceback (most recent call last):
  File "/home/il55/cell2loc_env/lib/python3.9/site-packages/anndata/_io/utils.py", line 246, in func_wrapper
    return func(*args, **kwargs)
  File "/home/il55/cell2loc_env/lib/python3.9/site-packages/anndata/_io/specs/registry.py", line 311, in write_elem
    return write_func(store, k, elem, dataset_kwargs=dataset_kwargs)
  File "/home/il55/cell2loc_env/lib/python3.9/site-packages/anndata/_io/specs/registry.py", line 52, in wrapper
    result = func(g, k, *args, **kwargs)
  File "/home/il55/cell2loc_env/lib/python3.9/site-packages/anndata/_io/specs/methods.py", line 359, in write_vlen_string_array
    f.create_dataset(k, data=elem.astype(str_dtype), dtype=str_dtype, **dataset_kwargs)
  File "/home/il55/cell2loc_env/lib/python3.9/site-packages/h5py/_hl/group.py", line 183, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/home/il55/cell2loc_env/lib/python3.9/site-packages/h5py/_hl/dataset.py", line 166, in make_new_dset
    dset_id.write(h5s.ALL, h5s.ALL, data)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 283, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 145, in h5py._proxy.dset_rw
  File "h5py/_conv.pyx", line 444, in h5py._conv.str2vlen
  File "h5py/_conv.pyx", line 95, in h5py._conv.generic_converter
  File "h5py/_conv.pyx", line 249, in h5py._conv.conv_str2vlen
TypeError: Can't implicitly convert non-string objects to strings

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/il55/cell2loc_env/lib/python3.9/site-packages/anndata/_core/anndata.py", line 1959, in write_h5ad
    _write_h5ad(
  File "/home/il55/cell2loc_env/lib/python3.9/site-packages/anndata/_io/h5ad.py", line 92, in write_h5ad
    write_elem(f, "obs", adata.obs, dataset_kwargs=dataset_kwargs)
  File "/home/il55/cell2loc_env/lib/python3.9/site-packages/anndata/_io/specs/registry.py", line 353, in write_elem
    Writer(_REGISTRY).write_elem(store, k, elem, dataset_kwargs=dataset_kwargs)
  File "/home/il55/cell2loc_env/lib/python3.9/site-packages/anndata/_io/utils.py", line 248, in func_wrapper
    re_raise_error(e, elem, key)
  File "/home/il55/cell2loc_env/lib/python3.9/site-packages/anndata/_io/utils.py", line 246, in func_wrapper
    return func(*args, **kwargs)
  File "/home/il55/cell2loc_env/lib/python3.9/site-packages/anndata/_io/specs/registry.py", line 311, in write_elem
    return write_func(store, k, elem, dataset_kwargs=dataset_kwargs)
  File "/home/il55/cell2loc_env/lib/python3.9/site-packages/anndata/_io/specs/registry.py", line 52, in wrapper
    result = func(g, k, *args, **kwargs)
  File "/home/il55/cell2loc_env/lib/python3.9/site-packages/anndata/_io/specs/methods.py", line 579, in write_dataframe
    _writer.write_elem(
  File "/home/il55/cell2loc_env/lib/python3.9/site-packages/anndata/_io/utils.py", line 248, in func_wrapper
    re_raise_error(e, elem, key)
  File "/home/il55/cell2loc_env/lib/python3.9/site-packages/anndata/_io/utils.py", line 229, in re_raise_error
    raise type(e)(
TypeError: Can't implicitly convert non-string objects to strings

Above error raised while writing key 'in_tissue' of <class 'h5py._hl.group.Group'> to /
```

**Comment by jil100** [comment]
@vitkl Thank you for your quick response. It was indeed an issue with scanpy spatial plotting.
