### ISSUE TITLE
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled

### ISSUE THREAD

**Issue by ciciQ777** [BayraktarLab/cell2location#55]
Hi

Thanks for developing the cell2location package. When I run the tutorial and import cell2location, I met this error:

```
os.environ["THEANO_FLAGS"] = 'device=cuda0,floatX=' + data_type + ',force_device=True
import cell2location
/home/cici/.conda/envs/cellpymc/lib/python3.7/site-packages/theano/gpuarray/dnn.py:184: UserWarning: Your cuDNN version is more recent than Theano. If you encounter problems, try updating Theano or downgrading cuDNN to a version >= v5 and <= v7.
  warnings.warn("Your cuDNN version is more recent than "
Using cuDNN version 7600 on context None
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/home/cici/.conda/envs/cellpymc/lib/python3.7/site-packages/theano/gpuarray/__init__.py", line 227, in <module>
    use(config.device)
  File "/home/cici/.conda/envs/cellpymc/lib/python3.7/site-packages/theano/gpuarray/__init__.py", line 214, in use
    init_dev(device, preallocate=preallocate)
  File "/home/cici/.conda/envs/cellpymc/lib/python3.7/site-packages/theano/gpuarray/__init__.py", line 159, in init_dev
    pygpu.blas.gemm(0, tmp, tmp, 0, tmp, overwrite_c=True)
  File "pygpu/blas.pyx", line 149, in pygpu.blas.gemm
  File "pygpu/blas.pyx", line 47, in pygpu.blas.pygpu_blas_rgemm
pygpu.gpuarray.GpuArrayException: (b'cublasCreate: (cublas) Library not initialized. (Possibly because the driver version is too old for the cuda version)', 11)
```
And this is the output when I type 'nvidia-smi': 
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:05:00.0 Off |                  N/A |
|  0%   32C    P8    16W / 280W |    291MiB / 11176MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Quadro K2000        Off  | 00000000:06:00.0 Off |                  N/A |
| 30%   44C    P0    N/A /  N/A |      0MiB /  1999MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

It seems that the Driver is not too old for the cuba version. I also tried to reinstall theano, but it does not help. Could you please provide me some suggestions on how to fix the error?

Thanks!

**Comment by vitkl** [comment]
Hi @ciciQ777

Are you using the singularity/docker images?

**Comment by ddfishbean** [comment]
Same issue here! Using the conda cellpymc environment but not the singularity/docker images. Any suggestions will be very appreciated!

**Comment by vitkl** [comment]
Try installing using ylm file as shown here: https://github.com/BayraktarLab/cell2location/blob/master/README.md#1-method-1-preferred-create-environment-from-file
