### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by cherrie-g** [BayraktarLab/cell2location#60]
hi, 
       I have installed the cell2location packages with Conda. My Linux is Centos7. But when I suppose to import the package in Python, it ended for this error :
You can find the C code in this temporary file: /tmp/theano_compilation_error_5q0kyagy
library inux-gnu/4.9.3/cc1plus: is not found.
Traceback (most recent call last):
  File "path/miniconda/envs/cellpymc/lib/python3.7/site-packages/theano/gof/lazylinker_c.py", line 81, in <module>
    actual_version, force_compile, _need_reload))
ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "path/miniconda/envs/cellpymc/lib/python3.7/site-packages/theano/gof/lazylinker_c.py", line 105, in <module>
    actual_version, force_compile, _need_reload))
ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "path/miniconda/envs/cellpymc/lib/python3.7/site-packages/cell2location/__init__.py", line 2, in <module>
    from .run_c2l import run_cell2location
  File "path/miniconda/envs/cellpymc/lib/python3.7/site-packages/cell2location/run_c2l.py", line 9, in <module>
    import theano
  File "path/miniconda/envs/cellpymc/lib/python3.7/site-packages/theano/__init__.py", line 110, in <module>
    from theano.compile import (
  File "path/miniconda/envs/cellpymc/lib/python3.7/site-packages/theano/compile/__init__.py", line 12, in <module>
    from theano.compile.mode import *
  File "path/miniconda/envs/cellpymc/lib/python3.7/site-packages/theano/compile/mode.py", line 11, in <module>
    import theano.gof.vm
  File "path/miniconda/envs/cellpymc/lib/python3.7/site-packages/theano/gof/vm.py", line 674, in <module>
    from . import lazylinker_c
  File "path/miniconda/envs/cellpymc/lib/python3.7/site-packages/theano/gof/lazylinker_c.py", line 140, in <module>
    preargs=args)
  File "path/miniconda/envs/cellpymc/lib/python3.7/site-packages/theano/gof/cmodule.py", line 2411, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: Compilation failed (return status=1): path/gcc-4.9.3/libexec/gcc/x86_64-unknown-linux-gnu/4.9.3/cc1plus: error while loading shared libraries: libmpfr.so.1: cannot open shared object file: No such file or directory.

Does this error was caused by my system environment or something others? How can I fix it?
Thanks

**Comment by vitkl** [comment]
Hi @cherrie-g 

We are finalising a major revision of cell2location including backend and user interface. Please have a look at the new installation instructions and a new tutorial. This should prevent similar theano-related issues.

**Comment by cherrie-g** [comment]
I have installed the new version. But it still not work and report the same errors. Could it be some other reasons?

**Comment by vitkl** [comment]
Are you doing the analysis according to the new tutorial? It should not be using theano.

**Comment by cherrie-g** [comment]
I'm sorry but where can I find the new tutorial?

**Comment by vitkl** [comment]
I mean that tutorial exactly. Are you trying to use it on Google Colab?

You need to first install cell2location as described in the readme. Then
use the tutorial.

Those lines installing cell2location using pip should not become active
unless you are on Colab
